package com.wbg.sums.service;

import com.wbg.sums.entity.Admin;
import org.apache.ibatis.annotations.Param;

import java.util.List;


public interface AdminService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated
     */
    int insert(Admin record);
    int count(@Param("status")String status);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated
     */
    Admin selectByPrimaryKey(Integer aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated
     */
    List<Admin> selectAll();

    int updateByPrimaryKey(Admin record);

    int updatePassword(@Param("a_username") String a_username, @Param("a_password") String a_password);

    int selectUserName(@Param("a_username") String a_username);
    int updateStatus(@Param("a_username") String a_username,@Param("status")  String status);

    List<Admin> selectAllVague(@Param("a_username") String a_username);
    List<Admin> selectAllStatus(@Param("status")String status);
}
