package com.wbg.sums.service;

import com.wbg.sums.entity.Attendance;

import java.util.List;

public interface AttendanceService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer aId);

    int count();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated
     */
    int insert(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated
     */
    Attendance selectByPrimaryKey(Integer aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated
     */
    List<Attendance> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Attendance record);
}
