package com.wbg.sums.service;

import com.wbg.sums.entity.FinancialManagement;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;

public interface FinancialManagementService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_management
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer fId);
    //获取当前余额
    BigDecimal selectMoney();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_management
     *
     * @mbg.generated
     */
    int insert(FinancialManagement record);
    int count();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_management
     *
     * @mbg.generated
     */
    FinancialManagement selectByPrimaryKey(Integer fId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_management
     *
     * @mbg.generated
     */
    List<FinancialManagement> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financial_management
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FinancialManagement record);
    List<FinancialManagement> selectGroupBymName();


    List<FinancialManagement> selects(@Param("mName") String mName, @Param("fType") String fType, @Param("beforeDate") String beforeDate, @Param("afterDate") String afterDate);

    int counts(@Param("mName") String mName,@Param("fType") String fType, @Param("beforeDate") String beforeDate, @Param("afterDate") String afterDate);

}
