package com.wbg.sums.service;

import com.wbg.sums.entity.Jurisdiction;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface JurisdictionService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer jId);
    int count(@Param("name")String name, @Param("url")String url);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated
     */
    int insert(Jurisdiction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated
     */
    Jurisdiction selectByPrimaryKey(Integer jId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated
     */
    List<Jurisdiction> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Jurisdiction record);

    int updateName(@Param("j_id")int j_id,@Param("j_name") String j_name);

    int updateUrl(@Param("j_id")int j_id, @Param("url") String url);

    List<Jurisdiction> selectName(@Param("name")String name);

}
