package com.wbg.sums.service;

import com.wbg.sums.entity.LeaveRecord;

import java.util.List;

public interface LeaveRecordService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer lId);
    int count();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_record
     *
     * @mbg.generated
     */
    int insert(LeaveRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_record
     *
     * @mbg.generated
     */
    LeaveRecord selectByPrimaryKey(Integer lId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_record
     *
     * @mbg.generated
     */
    List<LeaveRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LeaveRecord record);

    //    根据部门、请假时间查询请假记录int selectName(String d_name,String p_date);
    int selectName(String d_name,String p_date);

    //    根据成员工作编号查询请假记录 List<LeaveRecord> selectByMid(String m_user);
    List<LeaveRecord> selectByMid(String m_user);
}
