package com.wbg.sums.service;

import com.wbg.sums.entity.MonthlyPlanSummary;

import java.util.List;

public interface MonthlyPlanSummaryService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_plan_summary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer mId);
    int count();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_plan_summary
     *
     * @mbg.generated
     */
    int insert(MonthlyPlanSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_plan_summary
     *
     * @mbg.generated
     */
    MonthlyPlanSummary selectByPrimaryKey(Integer mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_plan_summary
     *
     * @mbg.generated
     */
    List<MonthlyPlanSummary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_plan_summary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MonthlyPlanSummary record);

}
