package com.wbg.sums.service;

import com.wbg.sums.entity.PositionType;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PositionTypeService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_type
     *
     * @mbg.generated
     */
    int insert(PositionType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_type
     *
     * @mbg.generated
     */
    PositionType selectByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_type
     *
     * @mbg.generated
     */
    List<PositionType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_type
     *
     * @mbg.generated
     */

    int count(String status);
    int updateByPrimaryKey(PositionType record);

    //    根据p_id修改状态    int updateStatus(int p_id, String status);
    int updateStatus(@Param("p_id") int p_id, @Param("status") String status);

    //    update PositionType set status=#{status} where p_id=#{p_id}
//    根据p_id修改顺序   int updateSort(int p_id, int p_sort);
    int updateSort(@Param("p_id")int p_id,@Param("p_sort") int p_sort);

    //    update PositionType set p_sort=#{p_sort} where p_id=#{p_id}
//    根据状态查询全部      List<PositionType> selectAllStatus(String status);
    List<PositionType> selectAllStatus(@Param("status")String status);

    //    select * from PositionType where status={#status}
//    根据状态查询编号、名称     List<PositionType> iselectAllStatus(String status);
    List<PositionType> iselectAllStatus(@Param("status")String status);

    //     select p_id,p_name from PositionType where status={#status}
//     模糊名称查询  List<PositionType> selectAllVague(String p_name);
    List<PositionType> selectAllVague(@Param("p_name")String p_name);
//     select *  from PositionType where  p_name like  concat('%',#{ p_name},'%')

}
