package com.wbg.sums.service;

import com.wbg.sums.entity.VerificationCode;

import java.util.List;

public interface VerificationCodeService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verificationcode
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verificationcode
     *
     * @mbg.generated
     */
    int insert(VerificationCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verificationcode
     *
     * @mbg.generated
     */
    VerificationCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verificationcode
     *
     * @mbg.generated
     */
    List<VerificationCode> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verificationcode
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VerificationCode record);
}
