package com.wbg.sums.entity;
public class Admin {


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_id
     *
     * @mbg.generated
     */
    private Integer aId;


    @Override
    public String toString() {
        return "Admin{" +
                "aId=" + aId +
                ", aUsername='" + aUsername + '\'' +
                ", aPassword='" + aPassword + '\'' +
                ", status='" + status + '\'' +
                ", aRemarks='" + aRemarks + '\'' +
                '}';
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_username
     *
     * @mbg.generated
     */
    private String aUsername;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_password
     *
     * @mbg.generated
     */

    private String aPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_remarks
     *
     * @mbg.generated
     */
    private String aRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_id
     *
     * @return the value of admin.a_id
     *
     * @mbg.generated
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_id
     *
     * @param aId the value for admin.a_id
     *
     * @mbg.generated
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_username
     *
     * @return the value of admin.a_username
     *
     * @mbg.generated
     */
    public String getaUsername() {
        return aUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_username
     *
     * @param aUsername the value for admin.a_username
     *
     * @mbg.generated
     */
    public void setaUsername(String aUsername) {
        this.aUsername = aUsername == null ? null : aUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_password
     *
     * @return the value of admin.a_password
     *
     * @mbg.generated
     */
    public String getaPassword() {
        return aPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_password
     *
     * @param aPassword the value for admin.a_password
     *
     * @mbg.generated
     */
    public void setaPassword(String aPassword) {
        this.aPassword = aPassword == null ? null : aPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.status
     *
     * @return the value of admin.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.status
     *
     * @param status the value for admin.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_remarks
     *
     * @return the value of admin.a_remarks
     *
     * @mbg.generated
     */
    public String getaRemarks() {
        return aRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_remarks
     *
     * @param aRemarks the value for admin.a_remarks
     *
     * @mbg.generated
     */
    public void setaRemarks(String aRemarks) {
        this.aRemarks = aRemarks == null ? null : aRemarks.trim();
    }
}