package com.wbg.sums.entity;

import java.util.Date;

public class Attendance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.a_id
     *
     * @mbg.generated
     */
    private Integer aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.a_type
     *
     * @mbg.generated
     */
    private String aType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.m_user
     *
     * @mbg.generated
     */
    private Integer mUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.d_name
     *
     * @mbg.generated
     */
    private String dName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.a_titile
     *
     * @mbg.generated
     */
    private String aTitile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.a_date
     *
     * @mbg.generated
     */
    private Date aDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.a_m_id
     *
     * @mbg.generated
     */
    private Integer aMId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.a_remaks
     *
     * @mbg.generated
     */
    private String aRemaks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.a_id
     *
     * @return the value of attendance.a_id
     *
     * @mbg.generated
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.a_id
     *
     * @param aId the value for attendance.a_id
     *
     * @mbg.generated
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.a_type
     *
     * @return the value of attendance.a_type
     *
     * @mbg.generated
     */
    public String getaType() {
        return aType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.a_type
     *
     * @param aType the value for attendance.a_type
     *
     * @mbg.generated
     */
    public void setaType(String aType) {
        this.aType = aType == null ? null : aType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.m_user
     *
     * @return the value of attendance.m_user
     *
     * @mbg.generated
     */
    public Integer getmUser() {
        return mUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.m_user
     *
     * @param mUser the value for attendance.m_user
     *
     * @mbg.generated
     */
    public void setmUser(Integer mUser) {
        this.mUser = mUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.d_name
     *
     * @return the value of attendance.d_name
     *
     * @mbg.generated
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.d_name
     *
     * @param dName the value for attendance.d_name
     *
     * @mbg.generated
     */
    public void setdName(String dName) {
        this.dName = dName == null ? null : dName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.a_titile
     *
     * @return the value of attendance.a_titile
     *
     * @mbg.generated
     */
    public String getaTitile() {
        return aTitile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.a_titile
     *
     * @param aTitile the value for attendance.a_titile
     *
     * @mbg.generated
     */
    public void setaTitile(String aTitile) {
        this.aTitile = aTitile == null ? null : aTitile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.a_date
     *
     * @return the value of attendance.a_date
     *
     * @mbg.generated
     */
    public Date getaDate() {
        return aDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.a_date
     *
     * @param aDate the value for attendance.a_date
     *
     * @mbg.generated
     */
    public void setaDate(Date aDate) {
        this.aDate = aDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.a_m_id
     *
     * @return the value of attendance.a_m_id
     *
     * @mbg.generated
     */
    public Integer getaMId() {
        return aMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.a_m_id
     *
     * @param aMId the value for attendance.a_m_id
     *
     * @mbg.generated
     */
    public void setaMId(Integer aMId) {
        this.aMId = aMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.a_remaks
     *
     * @return the value of attendance.a_remaks
     *
     * @mbg.generated
     */
    public String getaRemaks() {
        return aRemaks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.a_remaks
     *
     * @param aRemaks the value for attendance.a_remaks
     *
     * @mbg.generated
     */
    public void setaRemaks(String aRemaks) {
        this.aRemaks = aRemaks == null ? null : aRemaks.trim();
    }
}