package com.wbg.sums.entity;

import java.util.Date;

public class Backups {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backups.b_id
     *
     * @mbg.generated
     */
    private Integer bId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backups.b_beforedate
     *
     * @mbg.generated
     */
    private Date bBeforedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backups.b_file
     *
     * @mbg.generated
     */
    private String bFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backups.b_afterdate
     *
     * @mbg.generated
     */
    private Date bAfterdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backups.b_brefore_name
     *
     * @mbg.generated
     */
    private String bBreforeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column backups.b_after_name
     *
     * @mbg.generated
     */
    private String bAfterName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backups.b_id
     *
     * @return the value of backups.b_id
     *
     * @mbg.generated
     */
    public Integer getbId() {
        return bId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backups.b_id
     *
     * @param bId the value for backups.b_id
     *
     * @mbg.generated
     */
    public void setbId(Integer bId) {
        this.bId = bId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backups.b_beforedate
     *
     * @return the value of backups.b_beforedate
     *
     * @mbg.generated
     */
    public Date getbBeforedate() {
        return bBeforedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backups.b_beforedate
     *
     * @param bBeforedate the value for backups.b_beforedate
     *
     * @mbg.generated
     */
    public void setbBeforedate(Date bBeforedate) {
        this.bBeforedate = bBeforedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backups.b_file
     *
     * @return the value of backups.b_file
     *
     * @mbg.generated
     */
    public String getbFile() {
        return bFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backups.b_file
     *
     * @param bFile the value for backups.b_file
     *
     * @mbg.generated
     */
    public void setbFile(String bFile) {
        this.bFile = bFile == null ? null : bFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backups.b_afterdate
     *
     * @return the value of backups.b_afterdate
     *
     * @mbg.generated
     */
    public Date getbAfterdate() {
        return bAfterdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backups.b_afterdate
     *
     * @param bAfterdate the value for backups.b_afterdate
     *
     * @mbg.generated
     */
    public void setbAfterdate(Date bAfterdate) {
        this.bAfterdate = bAfterdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backups.b_brefore_name
     *
     * @return the value of backups.b_brefore_name
     *
     * @mbg.generated
     */
    public String getbBreforeName() {
        return bBreforeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backups.b_brefore_name
     *
     * @param bBreforeName the value for backups.b_brefore_name
     *
     * @mbg.generated
     */
    public void setbBreforeName(String bBreforeName) {
        this.bBreforeName = bBreforeName == null ? null : bBreforeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column backups.b_after_name
     *
     * @return the value of backups.b_after_name
     *
     * @mbg.generated
     */
    public String getbAfterName() {
        return bAfterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column backups.b_after_name
     *
     * @param bAfterName the value for backups.b_after_name
     *
     * @mbg.generated
     */
    public void setbAfterName(String bAfterName) {
        this.bAfterName = bAfterName == null ? null : bAfterName.trim();
    }
}