package com.wbg.sums.entity;

public class ClassTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_table.c_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_table.c_name
     *
     * @mbg.generated
     */
    private String cName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_table.c_headmaster_name
     *
     * @mbg.generated
     */
    private String cHeadmasterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_table.c_phone
     *
     * @mbg.generated
     */
    private String cPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_table.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_table.c_id
     *
     * @return the value of class_table.c_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_table.c_id
     *
     * @param cId the value for class_table.c_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_table.c_name
     *
     * @return the value of class_table.c_name
     *
     * @mbg.generated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_table.c_name
     *
     * @param cName the value for class_table.c_name
     *
     * @mbg.generated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_table.c_headmaster_name
     *
     * @return the value of class_table.c_headmaster_name
     *
     * @mbg.generated
     */
    public String getcHeadmasterName() {
        return cHeadmasterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_table.c_headmaster_name
     *
     * @param cHeadmasterName the value for class_table.c_headmaster_name
     *
     * @mbg.generated
     */
    public void setcHeadmasterName(String cHeadmasterName) {
        this.cHeadmasterName = cHeadmasterName == null ? null : cHeadmasterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_table.c_phone
     *
     * @return the value of class_table.c_phone
     *
     * @mbg.generated
     */
    public String getcPhone() {
        return cPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_table.c_phone
     *
     * @param cPhone the value for class_table.c_phone
     *
     * @mbg.generated
     */
    public void setcPhone(String cPhone) {
        this.cPhone = cPhone == null ? null : cPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_table.status
     *
     * @return the value of class_table.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_table.status
     *
     * @param status the value for class_table.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}