package com.wbg.sums.entity;

import java.util.Date;

public class DepartmentalExcellenceRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departmental_excellence_record.d_id
     *
     * @mbg.generated
     */
    private Integer dId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departmental_excellence_record.d_d_id
     *
     * @mbg.generated
     */
    private Integer dDId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departmental_excellence_record.d_title
     *
     * @mbg.generated
     */
    private String dTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departmental_excellence_record.d_date
     *
     * @mbg.generated
     */
    private Date dDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departmental_excellence_record.d_file
     *
     * @mbg.generated
     */
    private String dFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departmental_excellence_record.m_id
     *
     * @mbg.generated
     */
    private Integer mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departmental_excellence_record.d_contexts
     *
     * @mbg.generated
     */
    private String dContexts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departmental_excellence_record.d_id
     *
     * @return the value of departmental_excellence_record.d_id
     *
     * @mbg.generated
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departmental_excellence_record.d_id
     *
     * @param dId the value for departmental_excellence_record.d_id
     *
     * @mbg.generated
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departmental_excellence_record.d_d_id
     *
     * @return the value of departmental_excellence_record.d_d_id
     *
     * @mbg.generated
     */
    public Integer getdDId() {
        return dDId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departmental_excellence_record.d_d_id
     *
     * @param dDId the value for departmental_excellence_record.d_d_id
     *
     * @mbg.generated
     */
    public void setdDId(Integer dDId) {
        this.dDId = dDId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departmental_excellence_record.d_title
     *
     * @return the value of departmental_excellence_record.d_title
     *
     * @mbg.generated
     */
    public String getdTitle() {
        return dTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departmental_excellence_record.d_title
     *
     * @param dTitle the value for departmental_excellence_record.d_title
     *
     * @mbg.generated
     */
    public void setdTitle(String dTitle) {
        this.dTitle = dTitle == null ? null : dTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departmental_excellence_record.d_date
     *
     * @return the value of departmental_excellence_record.d_date
     *
     * @mbg.generated
     */
    public Date getdDate() {
        return dDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departmental_excellence_record.d_date
     *
     * @param dDate the value for departmental_excellence_record.d_date
     *
     * @mbg.generated
     */
    public void setdDate(Date dDate) {
        this.dDate = dDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departmental_excellence_record.d_file
     *
     * @return the value of departmental_excellence_record.d_file
     *
     * @mbg.generated
     */
    public String getdFile() {
        return dFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departmental_excellence_record.d_file
     *
     * @param dFile the value for departmental_excellence_record.d_file
     *
     * @mbg.generated
     */
    public void setdFile(String dFile) {
        this.dFile = dFile == null ? null : dFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departmental_excellence_record.m_id
     *
     * @return the value of departmental_excellence_record.m_id
     *
     * @mbg.generated
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departmental_excellence_record.m_id
     *
     * @param mId the value for departmental_excellence_record.m_id
     *
     * @mbg.generated
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departmental_excellence_record.d_contexts
     *
     * @return the value of departmental_excellence_record.d_contexts
     *
     * @mbg.generated
     */
    public String getdContexts() {
        return dContexts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departmental_excellence_record.d_contexts
     *
     * @param dContexts the value for departmental_excellence_record.d_contexts
     *
     * @mbg.generated
     */
    public void setdContexts(String dContexts) {
        this.dContexts = dContexts == null ? null : dContexts.trim();
    }
}