package com.wbg.sums.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class DepartmentalExcellenceRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departmental_excellence_record.d_id
     *
     * @mbg.generated
     */
    private Integer dId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departmental_excellence_record.d_d_id
     *
     * @mbg.generated
     */
    private String dName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departmental_excellence_record.d_title
     *
     * @mbg.generated
     */
    private String dTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departmental_excellence_record.d_date
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GTM+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date dDate;

    public Integer getdId() {
        return dId;
    }

    public void setdId(Integer dId) {
        this.dId = dId;
    }

    public String getdName() {
        return dName;
    }

    public void setdName(String dName) {
        this.dName = dName;
    }

    public String getdTitle() {
        return dTitle;
    }

    public void setdTitle(String dTitle) {
        this.dTitle = dTitle;
    }

    public Date getdDate() {
        return dDate;
    }

    public void setdDate(Date dDate) {
        this.dDate = dDate;
    }

    public String getdFile() {
        return dFile;
    }

    public void setdFile(String dFile) {
        this.dFile = dFile;
    }

    public String getmName() {
        return mName;
    }

    public void setmName(String mName) {
        this.mName = mName;
    }

    public String getdContexts() {
        return dContexts;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departmental_excellence_record.d_file
     *
     * @mbg.generated
     */
    private String dFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departmental_excellence_record.m_id
     *
     * @mbg.generated
     */
    private String mName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departmental_excellence_record.d_contexts
     *
     * @mbg.generated
     */
    private String dContexts;

    public void setdContexts(String dContexts) {
        this.dContexts = dContexts == null ? null : dContexts.trim();
    }
}