package com.wbg.sums.entity;

public class ExchangeTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_table.e_id
     *
     * @mbg.generated
     */
    private Integer eId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_table.e_name
     *
     * @mbg.generated
     */
    private String eName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_table.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_table.e_sort
     *
     * @mbg.generated
     */
    private Integer eSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_table.e_remarks
     *
     * @mbg.generated
     */
    private String eRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_table.e_id
     *
     * @return the value of exchange_table.e_id
     *
     * @mbg.generated
     */
    public Integer geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_table.e_id
     *
     * @param eId the value for exchange_table.e_id
     *
     * @mbg.generated
     */
    public void seteId(Integer eId) {
        this.eId = eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_table.e_name
     *
     * @return the value of exchange_table.e_name
     *
     * @mbg.generated
     */
    public String geteName() {
        return eName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_table.e_name
     *
     * @param eName the value for exchange_table.e_name
     *
     * @mbg.generated
     */
    public void seteName(String eName) {
        this.eName = eName == null ? null : eName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_table.status
     *
     * @return the value of exchange_table.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_table.status
     *
     * @param status the value for exchange_table.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_table.e_sort
     *
     * @return the value of exchange_table.e_sort
     *
     * @mbg.generated
     */
    public Integer geteSort() {
        return eSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_table.e_sort
     *
     * @param eSort the value for exchange_table.e_sort
     *
     * @mbg.generated
     */
    public void seteSort(Integer eSort) {
        this.eSort = eSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_table.e_remarks
     *
     * @return the value of exchange_table.e_remarks
     *
     * @mbg.generated
     */
    public String geteRemarks() {
        return eRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_table.e_remarks
     *
     * @param eRemarks the value for exchange_table.e_remarks
     *
     * @mbg.generated
     */
    public void seteRemarks(String eRemarks) {
        this.eRemarks = eRemarks == null ? null : eRemarks.trim();
    }
}