package com.wbg.sums.entity;

import java.math.BigDecimal;
import java.util.Date;

public class FinancialManagement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management.f_id
     *
     * @mbg.generated
     */
    private Integer fId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management.f_type
     *
     * @mbg.generated
     */
    private String fType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management.f_front_money
     *
     * @mbg.generated
     */
    private BigDecimal fFrontMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management.f_after_money
     *
     * @mbg.generated
     */
    private BigDecimal fAfterMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management.f_money
     *
     * @mbg.generated
     */
    private BigDecimal fMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management.f_date
     *
     * @mbg.generated
     */
    private Date fDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management.f_mr_date
     *
     * @mbg.generated
     */
    private Date fMrDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management.m_id
     *
     * @mbg.generated
     */
    private Integer mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management.f_remarks
     *
     * @mbg.generated
     */
    private String fRemarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financial_management.f_file
     *
     * @mbg.generated
     */
    private String fFile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management.f_id
     *
     * @return the value of financial_management.f_id
     *
     * @mbg.generated
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management.f_id
     *
     * @param fId the value for financial_management.f_id
     *
     * @mbg.generated
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management.f_type
     *
     * @return the value of financial_management.f_type
     *
     * @mbg.generated
     */
    public String getfType() {
        return fType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management.f_type
     *
     * @param fType the value for financial_management.f_type
     *
     * @mbg.generated
     */
    public void setfType(String fType) {
        this.fType = fType == null ? null : fType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management.f_front_money
     *
     * @return the value of financial_management.f_front_money
     *
     * @mbg.generated
     */
    public BigDecimal getfFrontMoney() {
        return fFrontMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management.f_front_money
     *
     * @param fFrontMoney the value for financial_management.f_front_money
     *
     * @mbg.generated
     */
    public void setfFrontMoney(BigDecimal fFrontMoney) {
        this.fFrontMoney = fFrontMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management.f_after_money
     *
     * @return the value of financial_management.f_after_money
     *
     * @mbg.generated
     */
    public BigDecimal getfAfterMoney() {
        return fAfterMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management.f_after_money
     *
     * @param fAfterMoney the value for financial_management.f_after_money
     *
     * @mbg.generated
     */
    public void setfAfterMoney(BigDecimal fAfterMoney) {
        this.fAfterMoney = fAfterMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management.f_money
     *
     * @return the value of financial_management.f_money
     *
     * @mbg.generated
     */
    public BigDecimal getfMoney() {
        return fMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management.f_money
     *
     * @param fMoney the value for financial_management.f_money
     *
     * @mbg.generated
     */
    public void setfMoney(BigDecimal fMoney) {
        this.fMoney = fMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management.f_date
     *
     * @return the value of financial_management.f_date
     *
     * @mbg.generated
     */
    public Date getfDate() {
        return fDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management.f_date
     *
     * @param fDate the value for financial_management.f_date
     *
     * @mbg.generated
     */
    public void setfDate(Date fDate) {
        this.fDate = fDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management.f_mr_date
     *
     * @return the value of financial_management.f_mr_date
     *
     * @mbg.generated
     */
    public Date getfMrDate() {
        return fMrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management.f_mr_date
     *
     * @param fMrDate the value for financial_management.f_mr_date
     *
     * @mbg.generated
     */
    public void setfMrDate(Date fMrDate) {
        this.fMrDate = fMrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management.m_id
     *
     * @return the value of financial_management.m_id
     *
     * @mbg.generated
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management.m_id
     *
     * @param mId the value for financial_management.m_id
     *
     * @mbg.generated
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management.f_remarks
     *
     * @return the value of financial_management.f_remarks
     *
     * @mbg.generated
     */
    public String getfRemarks() {
        return fRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management.f_remarks
     *
     * @param fRemarks the value for financial_management.f_remarks
     *
     * @mbg.generated
     */
    public void setfRemarks(String fRemarks) {
        this.fRemarks = fRemarks == null ? null : fRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financial_management.f_file
     *
     * @return the value of financial_management.f_file
     *
     * @mbg.generated
     */
    public String getfFile() {
        return fFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financial_management.f_file
     *
     * @param fFile the value for financial_management.f_file
     *
     * @mbg.generated
     */
    public void setfFile(String fFile) {
        this.fFile = fFile == null ? null : fFile.trim();
    }
}