package com.wbg.sums.entity;

public class Jurisdiction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction.j_id
     *
     * @mbg.generated
     */
    private Integer jId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction.j_name
     *
     * @mbg.generated
     */
    private String jName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction.j_remarks
     *
     * @mbg.generated
     */
    private String jRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction.j_id
     *
     * @return the value of jurisdiction.j_id
     *
     * @mbg.generated
     */
    public Integer getjId() {
        return jId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction.j_id
     *
     * @param jId the value for jurisdiction.j_id
     *
     * @mbg.generated
     */
    public void setjId(Integer jId) {
        this.jId = jId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction.j_name
     *
     * @return the value of jurisdiction.j_name
     *
     * @mbg.generated
     */
    public String getjName() {
        return jName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction.j_name
     *
     * @param jName the value for jurisdiction.j_name
     *
     * @mbg.generated
     */
    public void setjName(String jName) {
        this.jName = jName == null ? null : jName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction.status
     *
     * @return the value of jurisdiction.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction.status
     *
     * @param status the value for jurisdiction.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction.j_remarks
     *
     * @return the value of jurisdiction.j_remarks
     *
     * @mbg.generated
     */
    public String getjRemarks() {
        return jRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction.j_remarks
     *
     * @param jRemarks the value for jurisdiction.j_remarks
     *
     * @mbg.generated
     */
    public void setjRemarks(String jRemarks) {
        this.jRemarks = jRemarks == null ? null : jRemarks.trim();
    }
}