package com.wbg.sums.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class LeaveRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_record.l_id
     *
     * @mbg.generated
     */
    private Integer lId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_record.d_name
     *
     * @mbg.generated
     */
    private String dName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_record.m_user
     *
     * @mbg.generated
     */
    private Integer mUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_record.p_date
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd",timezone="GMT+8")
    private Date pDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_record.l_title
     *
     * @mbg.generated
     */
    private String lTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_record.l_type
     *
     * @mbg.generated
     */
    private String lType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_record.l_file
     *
     * @mbg.generated
     */
    private String lFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_record.l_m_id
     *
     * @mbg.generated
     */
    private String mName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_record.l_contexts
     *
     * @mbg.generated
     */
    private String lContexts;

    private String lMName;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_record.l_id
     *
     * @return the value of leave_record.l_id
     *
     * @mbg.generated
     */
    public Integer getlId() {
        return lId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_record.l_id
     *
     * @param lId the value for leave_record.l_id
     *
     * @mbg.generated
     */
    public void setlId(Integer lId) {
        this.lId = lId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_record.d_name
     *
     * @return the value of leave_record.d_name
     *
     * @mbg.generated
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_record.d_name
     *
     * @param dName the value for leave_record.d_name
     *
     * @mbg.generated
     */
    public void setdName(String dName) {
        this.dName = dName == null ? null : dName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_record.m_user
     *
     * @return the value of leave_record.m_user
     *
     * @mbg.generated
     */
    public Integer getmUser() {
        return mUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_record.m_user
     *
     * @param mUser the value for leave_record.m_user
     *
     * @mbg.generated
     */
    public void setmUser(Integer mUser) {
        this.mUser = mUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_record.p_date
     *
     * @return the value of leave_record.p_date
     *
     * @mbg.generated
     */
    public Date getpDate() {
        return pDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_record.p_date
     *
     * @param pDate the value for leave_record.p_date
     *
     * @mbg.generated
     */
    public void setpDate(Date pDate) {
        this.pDate = pDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_record.l_title
     *
     * @return the value of leave_record.l_title
     *
     * @mbg.generated
     */
    public String getlTitle() {
        return lTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_record.l_title
     *
     * @param lTitle the value for leave_record.l_title
     *
     * @mbg.generated
     */
    public void setlTitle(String lTitle) {
        this.lTitle = lTitle == null ? null : lTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_record.l_type
     *
     * @return the value of leave_record.l_type
     *
     * @mbg.generated
     */
    public String getlType() {
        return lType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_record.l_type
     *
     * @param lType the value for leave_record.l_type
     *
     * @mbg.generated
     */
    public void setlType(String lType) {
        this.lType = lType == null ? null : lType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_record.l_file
     *
     * @return the value of leave_record.l_file
     *
     * @mbg.generated
     */
    public String getlFile() {
        return lFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_record.l_file
     *
     * @param lFile the value for leave_record.l_file
     *
     * @mbg.generated
     */
    public void setlFile(String lFile) {
        this.lFile = lFile == null ? null : lFile.trim();
    }


    public String getmName() {
        return mName;
    }

    public void setmName(String mName) {
        this.mName = mName;
    }

    public String getlMName() {
        return lMName;
    }

    public void setlMName(String lMName) {
        this.lMName = lMName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_record.l_contexts
     *
     * @return the value of leave_record.l_contexts
     *
     * @mbg.generated
     */
    public String getlContexts() {
        return lContexts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_record.l_contexts
     *
     * @param lContexts the value for leave_record.l_contexts
     *
     * @mbg.generated
     */
    public void setlContexts(String lContexts) {
        this.lContexts = lContexts == null ? null : lContexts.trim();
    }
}