package com.wbg.sums.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;
public class MemberInformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_information.m_id
     *
     * @mbg.generated
     */
    private Integer mId;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_information.m_user
     *
     * @mbg.generated
     */
    private String mUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_information.m_password
     *
     * @mbg.generated
     */
    private String mPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_information.m_name
     *
     * @mbg.generated
     */
    private String mName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_information.m_sex
     *
     * @mbg.generated
     */
    private String mSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_information.c_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_information.c_phone
     *
     * @mbg.generated
     */
    private String cPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_information.d_id
     *
     * @mbg.generated
     */
    private Integer dId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_information.p_id
     *
     * @mbg.generated
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_information.p_photo
     *
     * @mbg.generated
     */
    private String pPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_information.e_id
     *
     * @mbg.generated
     */
    private Integer eId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_information.j_id
     *
     * @mbg.generated
     */
    private Integer jId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_information.m_qq
     *
     * @mbg.generated
     */
    private String mQq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_information.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_information.r_admission_date
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date rAdmissionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_information.r_tuihui_date
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date rTuihuiDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_information.p_remarks
     *
     * @mbg.generated
     */
    private String pRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_information.m_id
     *
     * @return the value of member_information.m_id
     *
     * @mbg.generated
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_information.m_id
     *
     * @param mId the value for member_information.m_id
     *
     * @mbg.generated
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_information.m_user
     *
     * @return the value of member_information.m_user
     *
     * @mbg.generated
     */
    public String getmUser() {
        return mUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_information.m_user
     *
     * @param mUser the value for member_information.m_user
     *
     * @mbg.generated
     */
    public void setmUser(String mUser) {
        this.mUser = mUser == null ? null : mUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_information.m_password
     *
     * @return the value of member_information.m_password
     *
     * @mbg.generated
     */
    public String getmPassword() {
        return mPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_information.m_password
     *
     * @param mPassword the value for member_information.m_password
     *
     * @mbg.generated
     */
    public void setmPassword(String mPassword) {
        this.mPassword = mPassword == null ? null : mPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_information.m_name
     *
     * @return the value of member_information.m_name
     *
     * @mbg.generated
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_information.m_name
     *
     * @param mName the value for member_information.m_name
     *
     * @mbg.generated
     */
    public void setmName(String mName) {
        this.mName = mName == null ? null : mName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_information.m_sex
     *
     * @return the value of member_information.m_sex
     *
     * @mbg.generated
     */
    public String getmSex() {
        return mSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_information.m_sex
     *
     * @param mSex the value for member_information.m_sex
     *
     * @mbg.generated
     */
    public void setmSex(String mSex) {
        this.mSex = mSex == null ? null : mSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_information.c_id
     *
     * @return the value of member_information.c_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_information.c_id
     *
     * @param cId the value for member_information.c_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_information.c_phone
     *
     * @return the value of member_information.c_phone
     *
     * @mbg.generated
     */
    public String getcPhone() {
        return cPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_information.c_phone
     *
     * @param cPhone the value for member_information.c_phone
     *
     * @mbg.generated
     */
    public void setcPhone(String cPhone) {
        this.cPhone = cPhone == null ? null : cPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_information.d_id
     *
     * @return the value of member_information.d_id
     *
     * @mbg.generated
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_information.d_id
     *
     * @param dId the value for member_information.d_id
     *
     * @mbg.generated
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_information.p_id
     *
     * @return the value of member_information.p_id
     *
     * @mbg.generated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_information.p_id
     *
     * @param pId the value for member_information.p_id
     *
     * @mbg.generated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_information.p_photo
     *
     * @return the value of member_information.p_photo
     *
     * @mbg.generated
     */
    public String getpPhoto() {
        return pPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_information.p_photo
     *
     * @param pPhoto the value for member_information.p_photo
     *
     * @mbg.generated
     */
    public void setpPhoto(String pPhoto) {
        this.pPhoto = pPhoto == null ? null : pPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_information.e_id
     *
     * @return the value of member_information.e_id
     *
     * @mbg.generated
     */
    public Integer geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_information.e_id
     *
     * @param eId the value for member_information.e_id
     *
     * @mbg.generated
     */
    public void seteId(Integer eId) {
        this.eId = eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_information.j_id
     *
     * @return the value of member_information.j_id
     *
     * @mbg.generated
     */
    public Integer getjId() {
        return jId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_information.j_id
     *
     * @param jId the value for member_information.j_id
     *
     * @mbg.generated
     */
    public void setjId(Integer jId) {
        this.jId = jId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_information.m_qq
     *
     * @return the value of member_information.m_qq
     *
     * @mbg.generated
     */
    public String getmQq() {
        return mQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_information.m_qq
     *
     * @param mQq the value for member_information.m_qq
     *
     * @mbg.generated
     */
    public void setmQq(String mQq) {
        this.mQq = mQq == null ? null : mQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_information.status
     *
     * @return the value of member_information.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_information.status
     *
     * @param status the value for member_information.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_information.r_admission_date
     *
     * @return the value of member_information.r_admission_date
     *
     * @mbg.generated
     */
    public Date getrAdmissionDate() {
        return rAdmissionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_information.r_admission_date
     *
     * @param rAdmissionDate the value for member_information.r_admission_date
     *
     * @mbg.generated
     */
    public void setrAdmissionDate(Date rAdmissionDate) {
        this.rAdmissionDate = rAdmissionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_information.r_tuihui_date
     *
     * @return the value of member_information.r_tuihui_date
     *
     * @mbg.generated
     */
    public Date getrTuihuiDate() {
        return rTuihuiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_information.r_tuihui_date
     *
     * @param rTuihuiDate the value for member_information.r_tuihui_date
     *
     * @mbg.generated
     */
    public void setrTuihuiDate(Date rTuihuiDate) {
        this.rTuihuiDate = rTuihuiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_information.p_remarks
     *
     * @return the value of member_information.p_remarks
     *
     * @mbg.generated
     */
    public String getpRemarks() {
        return pRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_information.p_remarks
     *
     * @param pRemarks the value for member_information.p_remarks
     *
     * @mbg.generated
     */
    public void setpRemarks(String pRemarks) {
        this.pRemarks = pRemarks == null ? null : pRemarks.trim();
    }
}