package com.wbg.sums.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class MinutesOfTheMeeting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minutes_of_the_meeting.m_id
     *
     * @mbg.generated
     */
    private Integer mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minutes_of_the_meeting.m_title
     *
     * @mbg.generated
     */
    private String mTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minutes_of_the_meeting.t_id
     *
     * @mbg.generated
     */
    private Integer tId;
    private TypeofMeeting typeOfMeeting;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minutes_of_the_meeting.m_date
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date mDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minutes_of_the_meeting.m_file
     *
     * @mbg.generated
     */
    private String mFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minutes_of_the_meeting.m_m_id
     *
     * @mbg.generated
     */
    private String mName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column minutes_of_the_meeting.m_contexts
     *
     * @mbg.generated
     */
    private String mContexts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minutes_of_the_meeting.m_id
     *
     * @return the value of minutes_of_the_meeting.m_id
     *
     * @mbg.generated
     */
    public Integer getmId() {
        return mId;
    }

    public TypeofMeeting getTypeOfMeeting() {
        return typeOfMeeting;
    }

    public void setTypeOfMeeting(TypeofMeeting typeOfMeeting) {
        this.typeOfMeeting = typeOfMeeting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minutes_of_the_meeting.m_id
     *
     * @param mId the value for minutes_of_the_meeting.m_id
     *
     * @mbg.generated
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minutes_of_the_meeting.m_title
     *
     * @return the value of minutes_of_the_meeting.m_title
     *
     * @mbg.generated
     */
    public String getmTitle() {
        return mTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minutes_of_the_meeting.m_title
     *
     * @param mTitle the value for minutes_of_the_meeting.m_title
     *
     * @mbg.generated
     */
    public void setmTitle(String mTitle) {
        this.mTitle = mTitle == null ? null : mTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minutes_of_the_meeting.t_id
     *
     * @return the value of minutes_of_the_meeting.t_id
     *
     * @mbg.generated
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minutes_of_the_meeting.t_id
     *
     * @param tId the value for minutes_of_the_meeting.t_id
     *
     * @mbg.generated
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minutes_of_the_meeting.m_date
     *
     * @return the value of minutes_of_the_meeting.m_date
     *
     * @mbg.generated
     */
    public Date getmDate() {
        return mDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minutes_of_the_meeting.m_date
     *
     * @param mDate the value for minutes_of_the_meeting.m_date
     *
     * @mbg.generated
     */
    public void setmDate(Date mDate) {
        this.mDate = mDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minutes_of_the_meeting.m_file
     *
     * @return the value of minutes_of_the_meeting.m_file
     *
     * @mbg.generated
     */
    public String getmFile() {
        return mFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minutes_of_the_meeting.m_file
     *
     * @param mFile the value for minutes_of_the_meeting.m_file
     *
     * @mbg.generated
     */
    public void setmFile(String mFile) {
        this.mFile = mFile == null ? null : mFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minutes_of_the_meeting.m_m_id
     *
     * @return the value of minutes_of_the_meeting.m_m_id
     *
     * @mbg.generated
     */
    public String getmName() {
        return mName;
    }

    public void setmName(String mName) {
        this.mName = mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column minutes_of_the_meeting.m_contexts
     *
     * @return the value of minutes_of_the_meeting.m_contexts
     *
     * @mbg.generated
     */
    public String getmContexts() {
        return mContexts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column minutes_of_the_meeting.m_contexts
     *
     * @param mContexts the value for minutes_of_the_meeting.m_contexts
     *
     * @mbg.generated
     */
    public void setmContexts(String mContexts) {
        this.mContexts = mContexts == null ? null : mContexts.trim();
    }
}