package com.wbg.sums.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Notic {
    public String getmName() {
        return mName;
    }

    public void setmName(String mName) {
        this.mName = mName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notic.n_id
     *
     * @mbg.generated
     */
    private Integer nId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notic.n_title
     *
     * @mbg.generated
     */
    private String nTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notic.n_date
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date nDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notic.n_file
     *
     * @mbg.generated
     */
    private String nFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notic.m_id
     *
     * @mbg.generated
     */
    private String mName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notic.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notic.n_context
     *
     * @mbg.generated
     */
    private String nContext;
private int nSort;

    public int getnSort() {
        return nSort;
    }

    public void setnSort(int nSort) {
        this.nSort = nSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notic.n_id
     *
     * @return the value of notic.n_id
     *
     * @mbg.generated
     */
    public Integer getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notic.n_id
     *
     * @param nId the value for notic.n_id
     *
     * @mbg.generated
     */
    public void setnId(Integer nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notic.n_title
     *
     * @return the value of notic.n_title
     *
     * @mbg.generated
     */
    public String getnTitle() {
        return nTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notic.n_title
     *
     * @param nTitle the value for notic.n_title
     *
     * @mbg.generated
     */
    public void setnTitle(String nTitle) {
        this.nTitle = nTitle == null ? null : nTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notic.n_date
     *
     * @return the value of notic.n_date
     *
     * @mbg.generated
     */
    public Date getnDate() {
        return nDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notic.n_date
     *
     * @param nDate the value for notic.n_date
     *
     * @mbg.generated
     */
    public void setnDate(Date nDate) {
        this.nDate = nDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notic.n_file
     *
     * @return the value of notic.n_file
     *
     * @mbg.generated
     */
    public String getnFile() {
        return nFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notic.n_file
     *
     * @param nFile the value for notic.n_file
     *
     * @mbg.generated
     */
    public void setnFile(String nFile) {
        this.nFile = nFile == null ? null : nFile.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notic.status
     *
     * @return the value of notic.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notic.status
     *
     * @param status the value for notic.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notic.n_context
     *
     * @return the value of notic.n_context
     *
     * @mbg.generated
     */
    public String getnContext() {
        return nContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notic.n_context
     *
     * @param nContext the value for notic.n_context
     *
     * @mbg.generated
     */
    public void setnContext(String nContext) {
        this.nContext = nContext == null ? null : nContext.trim();
    }
}