package com.wbg.sums.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class PersonalMeritRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_merit_record.p_id
     *
     * @mbg.generated
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_merit_record.d_name
     *
     * @mbg.generated
     */
    private String dName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_merit_record.m_id
     *
     * @mbg.generated
     */
    private String mUser;
    private String lMName;

    private String pTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_merit_record.p_date
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd" )
    private Date pDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_merit_record.p_file
     *
     * @mbg.generated
     */
    private String pFile;

    public Integer getpId() {
        return pId;
    }

    public void setpId(Integer pId) {
        this.pId = pId;
    }

    public String getdName() {
        return dName;
    }

    public void setdName(String dName) {
        this.dName = dName;
    }

    public String getmUser() {
        return mUser;
    }

    public void setmUser(String mUser) {
        this.mUser = mUser;
    }

    public String getlMName() {
        return lMName;
    }

    public void setlMName(String lMName) {
        this.lMName = lMName;
    }

    public String getpTitle() {
        return pTitle;
    }

    public void setpTitle(String pTitle) {
        this.pTitle = pTitle;
    }

    public Date getpDate() {
        return pDate;
    }

    public void setpDate(Date pDate) {
        this.pDate = pDate;
    }

    public String getpFile() {
        return pFile;
    }

    public void setpFile(String pFile) {
        this.pFile = pFile;
    }

    public String getmName() {
        return mName;
    }

    public void setmName(String mName) {
        this.mName = mName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_merit_record.p_m_id
     *
     * @mbg.generated
     */
    private String mName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_merit_record.p_contexts
     *
     * @mbg.generated
     */
    private String pContexts;

    public String getpContexts() {
        return pContexts;
    }

    public void setpContexts(String pContexts) {
        this.pContexts = pContexts == null ? null : pContexts.trim();
    }
}