package com.wbg.sums.entity;

import java.util.Date;

public class PersonalMeritRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_merit_record.p_id
     *
     * @mbg.generated
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_merit_record.d_name
     *
     * @mbg.generated
     */
    private String dName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_merit_record.m_id
     *
     * @mbg.generated
     */
    private Integer mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_merit_record.p_title
     *
     * @mbg.generated
     */
    private String pTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_merit_record.p_date
     *
     * @mbg.generated
     */
    private Date pDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_merit_record.p_file
     *
     * @mbg.generated
     */
    private String pFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_merit_record.p_m_id
     *
     * @mbg.generated
     */
    private Integer pMId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal_merit_record.p_contexts
     *
     * @mbg.generated
     */
    private String pContexts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_merit_record.p_id
     *
     * @return the value of personal_merit_record.p_id
     *
     * @mbg.generated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_merit_record.p_id
     *
     * @param pId the value for personal_merit_record.p_id
     *
     * @mbg.generated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_merit_record.d_name
     *
     * @return the value of personal_merit_record.d_name
     *
     * @mbg.generated
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_merit_record.d_name
     *
     * @param dName the value for personal_merit_record.d_name
     *
     * @mbg.generated
     */
    public void setdName(String dName) {
        this.dName = dName == null ? null : dName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_merit_record.m_id
     *
     * @return the value of personal_merit_record.m_id
     *
     * @mbg.generated
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_merit_record.m_id
     *
     * @param mId the value for personal_merit_record.m_id
     *
     * @mbg.generated
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_merit_record.p_title
     *
     * @return the value of personal_merit_record.p_title
     *
     * @mbg.generated
     */
    public String getpTitle() {
        return pTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_merit_record.p_title
     *
     * @param pTitle the value for personal_merit_record.p_title
     *
     * @mbg.generated
     */
    public void setpTitle(String pTitle) {
        this.pTitle = pTitle == null ? null : pTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_merit_record.p_date
     *
     * @return the value of personal_merit_record.p_date
     *
     * @mbg.generated
     */
    public Date getpDate() {
        return pDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_merit_record.p_date
     *
     * @param pDate the value for personal_merit_record.p_date
     *
     * @mbg.generated
     */
    public void setpDate(Date pDate) {
        this.pDate = pDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_merit_record.p_file
     *
     * @return the value of personal_merit_record.p_file
     *
     * @mbg.generated
     */
    public String getpFile() {
        return pFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_merit_record.p_file
     *
     * @param pFile the value for personal_merit_record.p_file
     *
     * @mbg.generated
     */
    public void setpFile(String pFile) {
        this.pFile = pFile == null ? null : pFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_merit_record.p_m_id
     *
     * @return the value of personal_merit_record.p_m_id
     *
     * @mbg.generated
     */
    public Integer getpMId() {
        return pMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_merit_record.p_m_id
     *
     * @param pMId the value for personal_merit_record.p_m_id
     *
     * @mbg.generated
     */
    public void setpMId(Integer pMId) {
        this.pMId = pMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal_merit_record.p_contexts
     *
     * @return the value of personal_merit_record.p_contexts
     *
     * @mbg.generated
     */
    public String getpContexts() {
        return pContexts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal_merit_record.p_contexts
     *
     * @param pContexts the value for personal_merit_record.p_contexts
     *
     * @mbg.generated
     */
    public void setpContexts(String pContexts) {
        this.pContexts = pContexts == null ? null : pContexts.trim();
    }
}