package com.wbg.sums.entity;

public class PositionType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_type.p_id
     *
     * @mbg.generated
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_type.p_name
     *
     * @mbg.generated
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_type.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_type.p_remarks
     *
     * @mbg.generated
     */
    private String pRemarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_type.p_sort
     *
     * @mbg.generated
     */
    private Integer pSort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_type.p_id
     *
     * @return the value of position_type.p_id
     *
     * @mbg.generated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_type.p_id
     *
     * @param pId the value for position_type.p_id
     *
     * @mbg.generated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_type.p_name
     *
     * @return the value of position_type.p_name
     *
     * @mbg.generated
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_type.p_name
     *
     * @param pName the value for position_type.p_name
     *
     * @mbg.generated
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_type.status
     *
     * @return the value of position_type.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_type.status
     *
     * @param status the value for position_type.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_type.p_remarks
     *
     * @return the value of position_type.p_remarks
     *
     * @mbg.generated
     */
    public String getpRemarks() {
        return pRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_type.p_remarks
     *
     * @param pRemarks the value for position_type.p_remarks
     *
     * @mbg.generated
     */
    public void setpRemarks(String pRemarks) {
        this.pRemarks = pRemarks == null ? null : pRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_type.p_sort
     *
     * @return the value of position_type.p_sort
     *
     * @mbg.generated
     */
    public Integer getpSort() {
        return pSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_type.p_sort
     *
     * @param pSort the value for position_type.p_sort
     *
     * @mbg.generated
     */
    public void setpSort(Integer pSort) {
        this.pSort = pSort;
    }
}