package com.wbg.sums.entity;

public class TypeofMeeting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typeof_meeting.t_id
     *
     * @mbg.generated
     */
    private Integer tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typeof_meeting.t_name
     *
     * @mbg.generated
     */
    private String tName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typeof_meeting.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typeof_meeting.t_remarks
     *
     * @mbg.generated
     */
    private String tRemarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typeof_meeting.t_sort
     *
     * @mbg.generated
     */
    private Integer tSort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typeof_meeting.t_id
     *
     * @return the value of typeof_meeting.t_id
     *
     * @mbg.generated
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typeof_meeting.t_id
     *
     * @param tId the value for typeof_meeting.t_id
     *
     * @mbg.generated
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typeof_meeting.t_name
     *
     * @return the value of typeof_meeting.t_name
     *
     * @mbg.generated
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typeof_meeting.t_name
     *
     * @param tName the value for typeof_meeting.t_name
     *
     * @mbg.generated
     */
    public void settName(String tName) {
        this.tName = tName == null ? null : tName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typeof_meeting.status
     *
     * @return the value of typeof_meeting.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typeof_meeting.status
     *
     * @param status the value for typeof_meeting.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typeof_meeting.t_remarks
     *
     * @return the value of typeof_meeting.t_remarks
     *
     * @mbg.generated
     */
    public String gettRemarks() {
        return tRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typeof_meeting.t_remarks
     *
     * @param tRemarks the value for typeof_meeting.t_remarks
     *
     * @mbg.generated
     */
    public void settRemarks(String tRemarks) {
        this.tRemarks = tRemarks == null ? null : tRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typeof_meeting.t_sort
     *
     * @return the value of typeof_meeting.t_sort
     *
     * @mbg.generated
     */
    public Integer gettSort() {
        return tSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typeof_meeting.t_sort
     *
     * @param tSort the value for typeof_meeting.t_sort
     *
     * @mbg.generated
     */
    public void settSort(Integer tSort) {
        this.tSort = tSort;
    }
}