package com.wbg.sums.entity;

import java.util.Date;

public class VerificationCode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verificationcode.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verificationcode.yzm
     *
     * @mbg.generated
     */
    private int yzm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verificationcode.v_type
     *
     * @mbg.generated
     */
    private String vType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verificationcode.v_date
     *
     * @mbg.generated
     */
    private Date vDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column verificationcode.v_phone
     *
     * @mbg.generated
     */
    private String vPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verificationcode.id
     *
     * @return the value of verificationcode.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verificationcode.id
     *
     * @param id the value for verificationcode.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verificationcode.yzm
     *
     * @return the value of verificationcode.yzm
     *
     * @mbg.generated
     */
    public int getYzm() {
        return yzm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verificationcode.yzm
     *
     * @param yzm the value for verificationcode.yzm
     *
     * @mbg.generated
     */
    public void setYzm(int yzm) {
        this.yzm = yzm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verificationcode.v_type
     *
     * @return the value of verificationcode.v_type
     *
     * @mbg.generated
     */
    public String getvType() {
        return vType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verificationcode.v_type
     *
     * @param vType the value for verificationcode.v_type
     *
     * @mbg.generated
     */
    public void setvType(String vType) {
        this.vType = vType == null ? null : vType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verificationcode.v_date
     *
     * @return the value of verificationcode.v_date
     *
     * @mbg.generated
     */
    public Date getvDate() {
        return vDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verificationcode.v_date
     *
     * @param vDate the value for verificationcode.v_date
     *
     * @mbg.generated
     */
    public void setvDate(Date vDate) {
        this.vDate = vDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column verificationcode.v_phone
     *
     * @return the value of verificationcode.v_phone
     *
     * @mbg.generated
     */
    public String getvPhone() {
        return vPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column verificationcode.v_phone
     *
     * @param vPhone the value for verificationcode.v_phone
     *
     * @mbg.generated
     */
    public void setvPhone(String vPhone) {
        this.vPhone = vPhone == null ? null : vPhone.trim();
    }
}