package com.wbg.sums.dao;

import com.wbg.sums.entity.Backups;
import java.util.List;

public interface BackupsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backups
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer bId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backups
     *
     * @mbg.generated
     */
    int insert(Backups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backups
     *
     * @mbg.generated
     */
    Backups selectByPrimaryKey(Integer bId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backups
     *
     * @mbg.generated
     */
    List<Backups> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table backups
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Backups record);
}