package com.wbg.sums.dao;

import com.wbg.sums.entity.ClassTable;
import com.wbg.sums.entity.ClassTable;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ClassTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cId);
    int count(String status);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_table
     *
     * @mbg.generated
     */
    int insert(ClassTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_table
     *
     * @mbg.generated
     */
    ClassTable selectByPrimaryKey(Integer cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_table
     *
     * @mbg.generated
     */
    List<ClassTable> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ClassTable record);

    //    根据c_id修改权限名称    int updateName(int c_id, String c_name);
    int updateName(@Param("c_id")int c_id,@Param("c_name") String c_name);

    //    update ClassTable set c_name=#{c_name} where c_id=#{c_id}
//    根据c_id修改状态  int updateStatus(int c_id, String status);
    int updateStatus(@Param("c_id")int c_id,@Param("status") String status);

    //    update ClassTable set status=#{status} where c_id=#{c_id}
//    模糊查询班主任名字     List<ClassTable> selectByName(String c_headmaster_name);
    List<ClassTable> selectByName(@Param("c_headmaster_name")String c_headmaster_name);

    //    select * from ClassTable where  c_headmaster_name like concat('%',#{c_headmaster_name},'%')
//    根据状态查询全部      List<ClassTable> selectAllStatus(String status);
    List<ClassTable> selectAllStatus(@Param("status")String status);

    //    select * from ClassTable where status=#{status}
//    根据状态查询编号、班级名称    List<ClassTable> iselectAllStatus(String status);
    List<ClassTable> iselectAllStatus(@Param("status")String status);
//    select c_id,c_name from ClassTable where status=#{status}
}