package com.wbg.sums.dao;

import com.wbg.sums.entity.DepartmentType;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DepartmentTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer dId);
    int count(String status);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbg.generated
     */
    int insert(DepartmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbg.generated
     */
    DepartmentType selectByPrimaryKey(Integer dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbg.generated
     */
    List<DepartmentType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DepartmentType record);

    //    根据id修改顺序 int updateSort(int d_id,int d_sort);
    int updateSort(@Param("d_id")int d_id, @Param("d_sort")int d_sort);

    //    update DepartmentType set d_sort=#{d_sort} where  d_id=#{d_id}
//    根据d_id修改状态 int updateStatus(int d_id, String status);
    int updateStatus(@Param("d_id")int d_id,@Param("status")String status);

    //    update DepartmentType set status=#{status} where  d_id=#{d_id}
//    根据d_name判断是否出现过该类型名称 int selectName(String d_name);
    int selectName(@Param("d_name")String d_name);

    //    select count(*) from DepartmentType where d_name=#{d_name}
//    根据状态全部查询  List<DepartmentType> selectAllStatus(String status);
    List<DepartmentType> selectAllStatus(@Param("status")String status);

    //    select *  from DepartmentType where status=#{status}
//    模糊部门名称全部查询     List<DepartmentType> selectAllVague(String d_name);
    List<DepartmentType> selectAllVague(@Param("d_name")String d_name);

    //    select *  from DepartmentType where d_name like  concat('%',#{ d_name},'%')
//    根据状态全部查询编号、名称  List<DepartmentType> iselectAllStatus(String status);
    List<DepartmentType> iselectAllStatus(@Param("status")String status);
//    select d_id,d_name  from DepartmentType where status=#{status}

}