package com.wbg.sums.dao;

import com.wbg.sums.entity.ExchangeTable;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ExchangeTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer eId);
    int count(String status);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_table
     *
     * @mbg.generated
     */
    int insert(ExchangeTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_table
     *
     * @mbg.generated
     */
    ExchangeTable selectByPrimaryKey(Integer eId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_table
     *
     * @mbg.generated
     */
    List<ExchangeTable> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExchangeTable record);

    //    根据e_id修改状态int updateStatus(int e_id,String status);
    int updateStatus(@Param("e_id") int e_id,@Param("status") String status);

    //    update ExchangeTable set status=#{status} where e_id=#{e_id}
//    根据e_id修改顺序 int updateSort(int e_id,int e_sort);
    int updateSort(@Param("e_id")int e_id,@Param("e_sort") int e_sort);

    //    update ExchangeTable set e_sort=#{e_sort} where e_id=#{e_id}
//    根据状态查询全部 List<ExchangeTable> selectAllStatus(String status);
    List<ExchangeTable> selectAllStatus(@Param("status")String status);

    //    select * from ExchangeTable where status={#status}
//    根据状态查询编号、名称  List<ExchangeTable> iselectAllStatus(String status);
    List<ExchangeTable> iselectAllStatus(@Param("status")String status);

    //     select e_id,e_name from ExchangeTable where status={#status}
//     模糊名称查询 List<ExchangeTable> selectAllVague(String e_name);
    List<ExchangeTable> selectAllVague(@Param("e_name")String e_name);
//      select *  from ExchangeTable where  e_name like  concat('%',#{e_name},'%')
}