package com.wbg.sums.dao;

import com.wbg.sums.entity.Jurisdiction;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface JurisdictionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer jId);
    int count(String status);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated
     */
    int insert(Jurisdiction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated
     */
    Jurisdiction selectByPrimaryKey(Integer jId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated
     */
    List<Jurisdiction> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Jurisdiction record);

    //    根据j_id修改权限名称 int updateName(int j_id, String j_name);
    int updateName(@Param("j_id")int j_id,@Param("j_name") String j_name);

    //    update Jurisdiction set j_name=#{j_name} where j_id=#{j_id}
//    根据j_id修改状态int updateStatus(int j_id, String status);
    int updateStatus(@Param("j_id")int j_id, @Param("status") String status);

    //    update Jurisdiction set status=#{status} where j_id=#{j_id}
//    根据状态查询全部 List<Jurisdiction> selectAllStatus(String status);
    List<Jurisdiction> selectAllStatus(@Param("status")String status);

    //    select * from Jurisdiction where status=#{status}
//    根据状态查询编号、名称 List<Jurisdiction> iselectAllStatus(String status);
    List<Jurisdiction> iselectAllStatus(@Param("status")String status);

    //    select * from Jurisdiction where status=#{status}
//    模糊权限名称全部查询 List<Jurisdiction> selectAllVague(String j_name);
    List<Jurisdiction> selectAllVague(@Param("j_name")String j_name);
//    select *  from Jurisdiction where j_name like  concat('%',#{ j_name},'%')


}