package com.wbg.sums.dao;

import com.wbg.sums.dto.MemberInfomationDto;
import com.wbg.sums.entity.MemberInformation;

import java.util.List;

public interface MemberInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_information
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_information
     *
     * @mbg.generated
     */
    int insert(MemberInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_information
     *
     * @mbg.generated
     */
    MemberInformation selectByPrimaryKey(Integer mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_information
     *
     * @mbg.generated
     */
    List<MemberInformation> selectAll();
    int count(String status);
    //多表连接查询
    List<MemberInfomationDto> selectTableAll(String status);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_information
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MemberInformation record);

    //    根据工作编号修改密码int updatePassword(String m_user,String m_password)
    int updatePassword(String m_user, String m_password);

    //    update MemberInformation set m_password=#{m_password} where m_user={m_user}
//    根据性别、班级、部门、职位、所属届、状态查询所有成员信息 List<MemberInformation> selectList(m_sex,c_id,d_id,p_id,e_id,status);
//(要求多表查询，使用mybatis判断字段传入为空时条件不成立)
    List<MemberInformation> selectList(String m_sex, int c_id, int d_id, int p_id, int e_id, String status);

    //    select m.m_id,m_user,m_name,m_sex,p_photo,m_qq,m.status,r_admission_date,m.p_remarks,c.c_name,c_headmaster_name,c.c_phone,d.d_name,p.p_name,e.e_name,j.j_name from MemberInformation m
//    join ClassTable c on c.c_id=m.c_id
//    join DepartmentType d on d.d_id=m.d_id
//    join PositionType p on p.p_id=m.p_id
//    join ExchangeTable e on e.e_id=m.e_id
//    join Jurisdiction j on j.j_id=m.j_id
//    根据姓名模糊查询、状态 List<MemberInformation> selectListNameStatus(m_name,status);
    List<MemberInformation> selectListNameStatus(String m_name, String status);

 //    select m.m_id,m_user,m_name,m_sex,p_photo,m_qq,m.status,r_admission_date,m.p_remarks,c.c_name,c_headmaster_name,c.c_phone,d.d_name,p.p_name,e.e_name,j.j_name from MemberInformation m
//    join ClassTable c on c.c_id=m.c_id
//    join DepartmentType d on d.d_id=m.d_id
//    join PositionType p on p.p_id=m.p_id
//    join ExchangeTable e on e.e_id=m.e_id
//    join Jurisdiction j on j.j_id=m.j_id
//    where m.status=#{status} and m.m_name like concat('%',#{m_name},'%')
//    根据成员编号修改成员照片 int updatePhoto(m_id, photo);
    int updatePhoto(int m_id, String photo);

    //    update MemberInformation  set photo=#{photo} where m_id=#{m_id}
    //    根据编号修改状态int updateStatus(m_id,status);
    int updateStatus(int m_id, String status);
//    update MemberInformation  set status=#{status} where m_id=#{m_id}

    //根据职位p_id查询所有名字和id
    List<MemberInformation> iSelectName(int pId);

    //根据mUser查询name
    List<MemberInformation> iUserName(String mUser);
}