package com.wbg.sums.dao;

import com.wbg.sums.entity.MonthlyPlanSummary;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MonthlyPlanSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_plan_summary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_plan_summary
     *
     * @mbg.generated
     */
    int insert(MonthlyPlanSummary record);
    int count();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_plan_summary
     *
     * @mbg.generated
     */
    MonthlyPlanSummary selectByPrimaryKey(Integer mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_plan_summary
     *
     * @mbg.generated
     */
    List<MonthlyPlanSummary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_plan_summary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MonthlyPlanSummary record);

    //根据时间查询
    List<MonthlyPlanSummary> selectDate(@Param("beforeDate") String beforeDate, @Param("afterDate") String afterDate);
    //根据操作员查询
    List<MonthlyPlanSummary> selectmName(@Param("mName") String mName);
    //根据部门查询
    List<MonthlyPlanSummary> selectdId(int dId);
   //查询多少条数据
    int counts(@Param("beforeDate") String beforeDate, @Param("afterDate") String afterDate, @Param("mName") String mName, @Param("dId") int dId);

}