package com.wbg.sums.dao;

import com.wbg.sums.entity.MonthlyPlanSummary;
import java.util.List;

public interface MonthlyPlanSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_plan_summary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_plan_summary
     *
     * @mbg.generated
     */
    int insert(MonthlyPlanSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_plan_summary
     *
     * @mbg.generated
     */
    MonthlyPlanSummary selectByPrimaryKey(Integer mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_plan_summary
     *
     * @mbg.generated
     */
    List<MonthlyPlanSummary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monthly_plan_summary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MonthlyPlanSummary record);

//    根据标题模糊查询 List<MonthlyPlanSummary> selectTitle(title);
//    根据时间、部门查询  List<MonthlyPlanSummary> selectTypedate(date，d_id);

}