package com.wbg.sums.dao;

import com.wbg.sums.entity.Notic;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface NoticMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer nId);
    int count(String status);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notic
     *
     * @mbg.generated
     */
    int insert(Notic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notic
     *
     * @mbg.generated
     */
    Notic selectByPrimaryKey(Integer nId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notic
     *
     * @mbg.generated
     */
    List<Notic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Notic record);

    //    根据标题模糊查询、状态查询List<Notic> selectTitlestatus(String n_title,String status);
    List<Notic> selectTitlestatus(@Param("nTitle")String nTitle,@Param("status") String status);

    //    select n.n_id,n_title,n_context,n_date,n_file,n.status,m.m_name from Notic n
//    join MemberInformation m on n.m_id=m.m_id
//    where status=#{status} and like n_title concat('%',#{n_title},'%'}
//      根据发布人查询、状态查询 List<Notic> selectMidStatus(int m_id,String status);
    List<Notic> selectMidStatus(@Param("mId") int mId,@Param("status") String status);

    //        select n.n_id,n_title,n_context,n_date,n_file,n.status,m.m_name from Notic n
//        join MemberInformation m on n.m_id=m.m_id
//        where m.m_id=#{m_id} and  status=#{status}
//        查询编号、标题、内容、发布人、发布时间List<Notic> iselectList(String status);
    List<Notic> iselectList(String status);

    //        select n.n_id,n_title,n_context,n_date,m.m_name from Notic n
//        join MemberInformation m on n.m_id=m.m_id
//        where status=#{status}
//        根据n_id修改状态 int updateStatus(int n_id,String status);
    int updateStatus(@Param("nId") int nId,@Param("status") String status);
//        update set status=#{status} where n_id=#{n_id}

}