package com.wbg.sums.dao;

import com.wbg.sums.entity.PersonalMeritRecord;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PersonalMeritRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_merit_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer pId);
    int count(@Param("lMName") String lMName);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_merit_record
     *
     * @mbg.generated
     */
    int insert(PersonalMeritRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_merit_record
     *
     * @mbg.generated
     */
    PersonalMeritRecord selectByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_merit_record
     *
     * @mbg.generated
     */
    List<PersonalMeritRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_merit_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PersonalMeritRecord record);

    List<PersonalMeritRecord> selectName(@Param("lMName") String lMName);


    //根据部门、时间查询  List<PersonalMeritRecord> selects(@Param("dName") String dName,@Param("beforeDate") String beforeDate,@Param("afterDate") String afterDate);
    List<PersonalMeritRecord> selects(@Param("dName") String dName, @Param("beforeDate") String beforeDate, @Param("afterDate") String afterDate);
    int counts(@Param("dName") String dName, @Param("beforeDate") String beforeDate, @Param("afterDate") String afterDate);

}