package com.wbg.sums.dao;

import com.wbg.sums.entity.WorkArrangement;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WorkArrangementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_arrangement
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer wId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_arrangement
     *
     * @mbg.generated
     */
    int insert(WorkArrangement record);

    int counts(@Param("dId") Integer dId,@Param("mName") String mName);
    int count(@Param("beforeDate") String beforeDate,@Param("afterDate") String afterDate);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_arrangement
     *
     * @mbg.generated
     */
    WorkArrangement selectByPrimaryKey(Integer wId);
    List<WorkArrangement> selectDate(@Param("beforeDate") String beforeDate,@Param("afterDate") String afterDate);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_arrangement
     *
     * @mbg.generated
     */
    List<WorkArrangement> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_arrangement
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WorkArrangement record);
    //获取不重复的标题
    List<WorkArrangement> selectGroupBy();

    //    模糊查询工作标题  List<WorkArrangement> selectAllVagueTitle(String w_title);
    List<WorkArrangement> selectAllVagueTitle(String wTitle);

    //    select w_id,w_title,w_contents,w_date,w_remarks,d.d_name,m.m_name,c_phone from WorkArrangement w
//    join MemberInformation m on m.m_id=w.m_id
//    join DepartmentType d on d.d_id=w.d_id where w_title like concat('%',#{w_title},'%')
//    根据部门查询所有工作 List<WorkArrangement> selectAllVagueName(int d_id);
    List<WorkArrangement> selectAllVagueName(int dId);
//    select w_id,w_title,w_contents,w_date,w_remarks,d.d_name,m.m_name,c_phone from WorkArrangement w
//    join MemberInformation m on m.m_id=w.m_id
//    join DepartmentType d on d.d_id=w.d_id where d.d_id=#{d_id}
    //根据负责人查询工作
    List<WorkArrangement> selectmName(String mName);

}